# Generated by Django 5.0.7 on 2024-10-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='workout_duration',
            field=models.IntegerField(blank=True, help_text='Workout duration in minutes', null=True),
        ),
    ]
