# Generated by Django 5.0.7 on 2024-10-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_age_alter_user_weight_alter_user_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
