# Generated by Django 5.0.7 on 2024-10-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userprofile_gender_remove_userprofile_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sex',
            new_name='gender',
        ),
    ]
