# Generated by Django 5.0.7 on 2024-10-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_sex_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_eaten',
            field=models.BooleanField(default=False),
        ),
    ]
