# Generated by Django 5.0.7 on 2024-10-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_food_is_eaten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='consumption_continuity',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
