# Generated by Django 5.0.7 on 2024-10-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('code', models.TextField()),
                ('api', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('Get', 'Get'), ('put', 'Put'), ('Delete', 'Delete'), ('Update', 'Update')], max_length=20)),
                ('type_lang', models.CharField(choices=[('language-markup', 'markup'), ('language-html', 'html'), ('language-xml', 'xml'), ('language-svg', 'svg'), ('language-mathml', 'mathml'), ('language-css', 'css'), ('language-clike', 'clike'), ('language-javascript', 'javascript'), ('language-abap', 'abap'), ('language-actionscript', 'actionscript'), ('language-ada', 'ada'), ('language-apacheconf', 'apacheconf'), ('language-apl', 'apl'), ('language-applescript', 'applescript'), ('language-arduino', 'arduino'), ('language-armasm', 'armasm'), ('language-aspnet', 'aspnet'), ('language-autohotkey', 'autohotkey'), ('language-autoit', 'autoit'), ('language-bash', 'bash'), ('language-basic', 'basic'), ('language-batch', 'batch'), ('language-bison', 'bison'), ('language-brainfuck', 'brainfuck'), ('language-c', 'c'), ('language-csharp', 'csharp'), ('language-cpp', 'cpp'), ('language-coffeescript', 'coffeescript'), ('language-crystal', 'crystal'), ('language-d', 'd'), ('language-dart', 'dart'), ('language-diff', 'diff'), ('language-django', 'django'), ('language-docker', 'docker'), ('language-eiffel', 'eiffel'), ('language-elixir', 'elixir'), ('language-elm', 'elm'), ('language-erlang', 'erlang'), ('language-flow', 'flow'), ('language-fortran', 'fortran'), ('language-fsharp', 'fsharp'), ('language-gherkin', 'gherkin'), ('language-git', 'git'), ('language-glsl', 'glsl'), ('language-go', 'go'), ('language-graphql', 'graphql'), ('language-groovy', 'groovy'), ('language-haml', 'haml'), ('language-handlebars', 'handlebars'), ('language-haskell', 'haskell'), ('language-haxe', 'haxe'), ('language-http', 'http'), ('language-idl', 'idl'), ('language-java', 'java'), ('language-jolie', 'jolie'), ('language-json', 'json'), ('language-julia', 'julia'), ('language-keyman', 'keyman'), ('language-kotlin', 'kotlin'), ('language-latex', 'latex'), ('language-less', 'less'), ('language-lisp', 'lisp'), ('language-livescript', 'livescript'), ('language-lua', 'lua'), ('language-makefile', 'makefile'), ('language-markdown', 'markdown'), ('language-matlab', 'matlab'), ('language-mel', 'mel'), ('language-mizar', 'mizar'), ('language-monkey', 'monkey'), ('language-n4js', 'n4js'), ('language-nasm', 'nasm'), ('language-nginx', 'nginx'), ('language-nim', 'nim'), ('language-nix', 'nix'), ('language-objectivec', 'objectivec'), ('language-ocaml', 'ocaml'), ('language-opencl', 'opencl'), ('language-oz', 'oz'), ('language-parigp', 'parigp'), ('language-parser', 'parser'), ('language-pascal', 'pascal'), ('language-perl', 'perl'), ('language-php', 'php'), ('language-powershell', 'powershell'), ('language-processing', 'processing'), ('language-prolog', 'prolog'), ('language-puppet', 'puppet'), ('language-pure', 'pure'), ('language-python', 'python'), ('language-q', 'q'), ('language-qore', 'qore'), ('language-r', 'r'), ('language-jsx', 'jsx'), ('language-tsx', 'tsx'), ('language-reason', 'reason'), ('language-ruby', 'ruby'), ('language-rust', 'rust'), ('language-sas', 'sas'), ('language-sass', 'sass'), ('language-scss', 'scss'), ('language-scala', 'scala'), ('language-scheme', 'scheme'), ('language-shell', 'shell'), ('language-smalltalk', 'smalltalk'), ('language-smarty', 'smarty'), ('language-solidity', 'solidity'), ('language-soy', 'soy'), ('language-sql', 'sql'), ('language-stylus', 'stylus'), ('language-swift', 'swift'), ('language-tcl', 'tcl'), ('language-textile', 'textile'), ('language-twig', 'twig'), ('language-typescript', 'typescript'), ('language-v', 'v'), ('language-vbnet', 'vbnet'), ('language-velocity', 'velocity'), ('language-verilog', 'verilog'), ('language-vhdl', 'vhdl'), ('language-vim', 'vim'), ('language-visualbasic', 'visualbasic'), ('language-wasm', 'wasm'), ('language-wiki', 'wiki'), ('language-xeora', 'xeora'), ('language-xojo', 'xojo'), ('language-xquery', 'xquery'), ('language-yaml', 'yaml')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
